openapi: 3.0.1
info:
  title: Car Online Shop
  description: Car Online Shop
  termsOfService: ""
  contact:
    email: abulynka@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1'
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/abulynka/cloud-development-course/1
- url: https://rawukoru6g.execute-api.eu-west-1.amazonaws.com/dev
tags:
- name: car
  description: Everything about your Cars
paths:
  /products:
    get:
      tags:
      - all products
      summary: Get All Products
      description: Get All Products
      operationId: getProductsList
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
        500:
          description: Internal Server Error
          content: {}
    post:
      tags:
      - new product
      summary: Add new Product
      description: Add new Product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarRequest'
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        500:
          description: Internal Server Error
          content: {}
  /products/{productId}:
    get:
      tags:
      - all products
      summary: Get All Products
      description: Get All Products
      operationId: getProductsById
      parameters:
      - name: productId
        in: path
        description: ID of product to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Car'
        500:
          description: Internal Server Error
          content: {}
components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: string
          format: string
        title:
          type: string
          format: string
        description:
          type: string
          format: string
        price:
          type: number
          format: number
        count:
          type: number
          format: number
    CarRequest:
      type: object
      properties:
        title:
          type: string
          format: string
        description:
          type: string
          format: string
        price:
          type: number
          format: number
        count:
          type: number
          format: number